#Database
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: letmein
POSTGRESQL_HOST: 10.0.0.162
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: docdatabase

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: reinert.isa@gmail.com
EMAIL_PASSWORD: ejdtffiqchtehjrf
VERIFY_EMAIL_HOST: http://localhost:8085

JWT_EXPIRATION: 432_000_000 #5 days
JWT_SECRET: ${SECRET}